### ISSUE TITLE
Data loss after connection problems

### ISSUE THREAD

**Issue by FritzHeiden** [nextcloud/documentserver_community#121]
Hello,
I just lost my entire document, because I had internet connection issues while editing the document. The file is still there, but its empty. I was working on the document multiple times, so there were multiple points where the document with all its content was stored on the nextcloud server.

I think this is a critical bug.

Thanks for your work anyway!

**Comment by LostinSpacetime** [comment]
This bug is here singe January but nobody seems to take care of it:
https://github.com/nextcloud/documentserver_community/issues/12
https://github.com/nextcloud/documentserver_community/issues/100
"Critical" is still an understatement in my opinion. They should stop publishing the Community Document Server as long as this is not fixed. People are loosing their work and Nextcloud it's credibility.

I would like to mark this bug as a duplicate but I don't know if I can.
