### ISSUE TITLE
App "documentserver_community"

### ISSUE THREAD

**Issue by evamaria60** [nextcloud/documentserver_community#160]
Hello,

when installing Community Document Server in Apps - Nextcloud,
an error has occurred.

The following is displayed:

"Documentserver_community app cannot be installed because appinfo file cannot be read."

What can I do?

Best Regards
Eva-Maria

**Comment by squeezer44** [comment]
Same for me: I just tried it twice and both times I saw the same message:
"Documentserver_community app cannot be installed because appinfo file cannot be read."

Used OS: Linux 3.18.117-pvops-xen-x64 x86_64
php Version: 7.3.6
MySQL DB Version: 5.6.19
NextCloud Version: nextcloud-19.0.0

- ErrorLogEntry

_[settings] Error: Exception: App "documentserver_community" cannot be installed because appinfo file cannot be read. at <<closure>>

0. /nextcloud-19.0.0/apps/settings/lib/Controller/AppSettingsController.php line 447
   OC\Installer->installApp("documentserver_community")
1. /nextcloud-19.0.0/lib/private/AppFramework/Http/Dispatcher.php line 170
   OCA\Settings\Controller\AppSettingsController->enableApps(["documentserver_community"], [])
2. /nextcloud-19.0.0/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "enableApps")
3. /nextcloud-19.0.0/lib/private/AppFramework/App.php line 137
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "enableApps")
4. /nextcloud-19.0.0/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", OC\AppFramework\ ... {}, {_route: "settin ... "})
5. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "settin ... "})
6. /nextcloud-19.0.0/lib/private/Route/Router.php line 297
   call_user_func(OC\AppFramework\ ... {}, {_route: "settin ... "})
7. /nextcloud-19.0.0/lib/base.php line 1007
   OC\Route\Router->match("/settings/apps/enable")
8. /nextcloud-19.0.0/index.php line 37
   OC::handleRequest()_

**Comment by evamaria60** [comment]
the same happens when installing Collabora Online - Built-in CODE Server..

**Comment by icewind1991** [comment]
Closing as duplicate of #26
