### ISSUE TITLE
Nextcloud 19.03 Community Document Server  not save 

### ISSUE THREAD

**Issue by FindschNET1** [nextcloud/documentserver_community#170]
the Community Document Server  Version 0.1.7 with ONLYOFFICE 6.0.0
dont save files and shows after reopen the onw User is working togehter with itself
![oonc19](https://user-images.githubusercontent.com/71878504/94256215-be51df00-ff29-11ea-968c-3d6d953fb5fe.PNG)

**Comment by ferdiga** [comment]
Hi, this is a high priority issue.
https://nextcloud.com/onlyoffice/
suggest a production ready solution.
Data loss is a no go (I just lost almost a days work)

perhaps the following description helps
I opened a xlsx in on window and the same xlsx in another window on the same computer.
changes in one window have been reflected correctly in the other window.
So I was convinced that data was written to the server.
I even clicked "file save" several times, because I wanted to be on the safe side.
Nevertheless it wasn't. 
After closing all windows and reopening the file all work was lost.
I also noted that the modification date was not changed.

I disabled ONLYOFFICE for now and enabled Collabora (which is much slower, lacks the freeze rows and columns feature, making sheets hard to use , supposedly solved in CODE 6.0 and the font resolution is not so good.). But at least no data loss.

All in all a very sub optimal solution.

**Comment by ferdiga** [comment]
see here
https://github.com/nextcloud/documentserver_community/issues/100

**Comment by FindschNET1** [comment]
THX for your input.
you're right all in all a very sub optimal solution.
i think it must be work... in need a solution!

**Comment by mhier** [comment]
As stated in #100, it works fine when not using the document server app but instead run the document server in a Docker container. The effort do to this is not very big.

Still, being able to use Onlyoffice with just a few clicks in Nextcloud (at least on small-scale installations) is quite neat. It has worked perfectly for me until the last update. If I remember correctly (cannot check any more, as I have switched now to the Docker version), the document server version provided by this app moved to version 6.0.0. This is strange, as the latest version is only 5.6.5. Maybe this is the actual root cause for the problem?

**Comment by ferdiga** [comment]
I didn't have much time, so I installed the docker document server and its running on port 8006,
I am lost what to do next.
* probably uninstall the nextcloud document server to be able to specify the new docker version ?
I do not get the 3 options in onlyoffice app,  I can remember it is the option 2  ?
* how make the docker server available to next cloud?
sorry for the stupid questions

**Comment by ferdiga** [comment]
can I drop these table to get a fresh install ?
```
MariaDB [owncloud]> show tables like "%documentserver%";
+---------------------------------------+
| Tables_in_owncloud (%documentserver%) |
+---------------------------------------+
| oc_documentserver_changes             |
| oc_documentserver_ipc                 |
| oc_documentserver_locks               |
| oc_documentserver_sess                |
+---------------------------------------+
4 rows in set (0.001 sec)

```

**Comment by mhier** [comment]
> I didn't have much time, so I installed the docker document server and its running on port 8006,
> I am lost what to do next.
> 
>     * probably uninstall the nextcloud document server to be able to specify the new docker version ?
>       I do not get the 3 options in onlyoffice app,  I can remember it is the option 2  ?

You can even keep the document server app in Nextcloud, it would simply be unused.


>     * how make the docker server available to next cloud?

In Nextcloud administrator settings, there is a ONLYOFFICE section. You have to put the document server address and the secret key (which you probably specified when launching the Docker container) in there.

As far as I understand, the document server needs to be reachable both by the Nextcloud instance as well as by the user's Browser. Hence if your Nextcloud instance is reachable from the internet, the document server should be reachable as well. It is also strongly recommended to use (only!) https for this, otherwise your documents are probably shipped in plain text through the internet. This is usually realised with a reverse proxy in Apache resp. nginx or whatever web server you are using.

Since this is not a support forum, maybe you should try to find the remaining information somewhere else (it's easily found in the big search engines...)

**Comment by ibnpetr** [comment]
> As far as I understand, the document server needs to be reachable both by the Nextcloud instance as well as by the user's Browser. Hence if your Nextcloud instance is reachable from the internet, the document server should be reachable as well.

one more thing:
Nextcloud also should be reachable by the document server (As soon as you close your editing session, ONLYOFFICE server will inform your NC instance that there is a new version of the document available in the document server's cache and it (NC) should download it)

**Comment by mhl66** [comment]
Does not save. Period. Ridiculous.

**Comment by ferdiga** [comment]
Please can anyone advice how to purge the only-office installation 
probably some old data prohibit the correct functioning.
I see tables associated with the community server and I think there was a section in ONLY Office to connect to an external onlyoffice (docker) service, which does nit show up any more.

**Comment by Fiodin** [comment]
I now switched to a Docker Instance of OnlyOffice. It really works fine and I wrote a little How-To without a reverse proxy because it was easier for me and it is as secure as it is with it: https://github.com/nextcloud/documentserver_community/issues/100#issuecomment-702423344

**Comment by mhl66** [comment]
NOTHING at all happened in the current versions (OnlyOffice 6.0.2 and Community Document Server 0.1.8).
This is really a show stopper for Nextcloud as a would-be office solution. Any comments at all???

**Comment by pongraczi** [comment]
+1  
* NC 19.0.4
* PHP 7.4
* Community Document Server 1.8
* Onlyoffice 6.0.2

### Use case:
* Shared excel sheet between users
* Only web clients involved to accessing the file
* Onlyoffice setting in NC:
  *  [x] Keep intermediate versions when editing (checked, aka force write)
* Onlyoffice editor settings under Advanced config:
  * [x] Automatic save enabled (checked)
  * [x] Cooperative editing set to quick 
  * [x] Always save to the server (otherwise save on close)
  * Force save to the server supposed to work with these settings
* Cronjobs
  * NC cronjob at */5   (cron.php)
  * occ document_flush  */2
  * occ email:send */2
* Saving/closing seems write out the file when one user edits and click on Save (timestamp seems fine, email notification sent almost immediately)

###Steps to reproduce and observations
* User1 opened, edited, saved, closed (by clicking on this
![Kijelölés_466](https://user-images.githubusercontent.com/5891983/96304015-b272ad80-0ffb-11eb-87f5-1b498f247beb.png)
* User1 reopened the file, added new record (several fields) save, leave
* User2 logs in from other location/browser, so, two NC session opened
* User2 opens the file in the browser: some fields are missing from the latest edition made by User1
* User2 saves, leaves
* User1 opens the file, it is definitely missing, same
![Kijelölés_462](https://user-images.githubusercontent.com/5891983/96304764-f6b27d80-0ffc-11eb-984b-288ca3d4e296.png)
* User1 added records , saves, leaves
* User2 opens the file, records exists as expected, added new record, save, leave (Observation: the number of users on the top right shows 2, even definitely only User2 edited the document)
* There are no running Onlyoffice in browser, all settings supposed to force write to server, timestamp and notification mentioned this, so, it should be no locks or sessions in the database (oc_documentserver_locks and oc_documentserver_sess)
* I found 2 existing sessions in the database and several locks
![Kijelölés_463](https://user-images.githubusercontent.com/5891983/96305164-bdc6d880-0ffd-11eb-890d-9ed73d67f279.png)
![Kijelölés_464](https://user-images.githubusercontent.com/5891983/96305478-37f75d00-0ffe-11eb-951d-a0659932c010.png)
* User1 opens, modifies, saves, leaves
* User2 opened, modified, keep onlyoffice open
* The database shows 3 existing sessions, even there only one active (running) Onlyoffice in browser
![Kijelölés_465](https://user-images.githubusercontent.com/5891983/96305438-2b730480-0ffe-11eb-8550-584669f190ac.png)

### My conclusion
```text
Big Fat Warning
* I do not know and I did not check how the session and lock mechanism are working in document server.
* Cronjob flushes every 2 minutes the documentserver.
```
```text
Quick Facts
* There were several locks and *ghost* sessions inside the database, while there was no active (running) Onlyoffice instances. I saw it for several minutes after all onlyoffice instances are closed.
* Every saves and leaves from Onlyoffice supposed to trigger force save to server and as I saw, it definitely happened (maybe one time, when there were several locks and three sessions, there was a small delay, I am not sure, maybe 1 minute).
```
* I suppose the correct behaviour should be that, when a user closes/leaves the Onlyoffice app, sessions should be wiped out immediately without delay.
* Locks are also interesting, I guess there should be no lock after saving, so, seeing several locks after everybody closed onlyoffice for several minutes should be an indicator of misbehaving.
* My bet the problem is lying around this lock and session anomaly.

### My request
Please share my report (this one) anywhere where you think it can help developers/others to fix this issue or give more data/test results to be able to narrow down the issue.

Let's fix this F rated issue. Thank you.

**Comment by pongraczi** [comment]
Today I just installed a standalone document server into an LXC container and set up with Nextcloud.  
I am testing right now and I have to tell, now it seems working as expected.  
I enter a lot of texts with User1 and User2 and there is no data loss, so far so good.  
Still testing, but much more promising than the bundled community document server.

**Comment by ferdiga** [comment]
I have installed Onlyoffice docker 6.0.0.105 and this seems to "work" so far. Changes are written to the Nextcloud storage and synced to the client.

I followed the guidance for "Force Saving" here:
https://api.onlyoffice.com/editors/save

```
{
    "services": {
        "CoAuthoring": {
            "autoAssembly": {
                "enable": true,
                "interval": "2m",
                "step": "1m" 
            }
        }
    }
}
```
Pls let me know your thoughts

**Comment by Fiodin** [comment]
You dont need the "Force Savong" with the Docker-Image. With it it is saved automatically.

**Comment by mhl66** [comment]
Summary: Docker works, this f***ing bu****it (aka Community Document Server) not. Anyone there?

**Comment by gcommit** [comment]
got the same problem and tried almost every solution out there. 

ONLYOFFICE Document Server is not equal to Community Docusment Server used for ONLYOFFICE by Nextcloud ...
