### ISSUE TITLE
Update to 0.1.8 version - Disappeared close button

### ISSUE THREAD

**Issue by Leprazoriy** [nextcloud/documentserver_community#174]
After updating to a new version 0.1.8, the button to close the document disappeared. Or should it be? Can I return the button?
!
[Close button](https://user-images.githubusercontent.com/72513510/95353816-63769b00-08cc-11eb-838c-0e0cdaf7782e.jpg)

**Comment by alex1702** [comment]
same problem

**Comment by jxohann** [comment]
same issue

**Comment by bes1002t** [comment]
The button is not gone, but hidden! Next to the Burger Menu there is a small folder button "Open file location", if you click this button the document will be closed.

But this is really very inconvenient and should be changed as soon as possible. The Document Server is like an overlay and the user always thinks the open directory is still in background. From a developer point of view this might be different, but this does not really matter since the user point of view is what we have to focus.

I think there should be a X button, as for every similar app like PDF viewer. Please replace the folder icon with an X.

**Comment by splitt3r** [comment]
> 
> 
> The button is not gone, but hidden! Next to the Burger Menu there is a small folder button "Open file location", if you click this button the document will be closed.
> 
> But this is really very inconvenient and should be changed as soon as possible. The Document Server is like an overlay and the user always thinks the open directory is still in background. From a developer point of view this might be different, but this does not really matter since the user point of view is what we have to focus.
> 
> I think there should be a X button, as for every similar app like PDF viewer. Please replace the folder icon with an X.

I think that button is a good alternative to the close button. But the wording of the label / description is pretty strange.

**Comment by zeigerpuppy** [comment]
I'm not sure that the "Open file location" does have the same function as the close button.  It gets the user out of the document but I think it leaves the documents session open.

Nnotice that exiting the document using "Open file location" and then reopening the document will increment the number of user sessions open for the document (in the "View Users and Manage Document Rights").

I think the close button is missing and will need to be found!

see also this related discussion - https://help.nextcloud.com/t/how-to-close-onlyoffice-window/70866/15

**Comment by bes1002t** [comment]
@zeigerpuppy but I think then there is no need for the "open file location" button. I think it would be better to replace that button with the close button.

**Comment by zeigerpuppy** [comment]
@bes1002t I agree, the "open file location" button is not really useful in the Nextcloud context.

**Comment by Exist2Resist** [comment]
> > The button is not gone, but hidden! Next to the Burger Menu there is a small folder button "Open file location", if you click this button the document will be closed.
> > But this is really very inconvenient and should be changed as soon as possible. The Document Server is like an overlay and the user always thinks the open directory is still in background. From a developer point of view this might be different, but this does not really matter since the user point of view is what we have to focus.
> > I think there should be a X button, as for every similar app like PDF viewer. Please replace the folder icon with an X.
> 
> I think that button is a good alternative to the close button. But the wording of the label / description is pretty strange.

It is not a good alternative to the close button because this does not close the session of the open documents. If you keep reopening the document the active sessions will keep growing. Additionally this can cause issues with the memory and with Redis. Please add close button that closes the session and exists the document.

**Comment by NEITG** [comment]
Any update on a resolution for this issue? Running 20.0.7 with OnlyOffice 6.3.0 and still no close button, using the open file location button as stated leaves sessions connected to the files.
