### ISSUE TITLE
Persisting "The community document server only supports up to 20 concurrent sessions" error message

### ISSUE THREAD

**Issue by drudgede** [nextcloud/documentserver_community#188]
Hello everyone,

since today, I always get the error message "The community document server only supports up to 20 concurrent sessions" when I try to open a document with the community document server.
However, there are no 20 concurrent sessions active. Interestingly, there are only a few users including me which get this error message while other users are able to start new sessions by opening a new document.

I also tried to reboot my server and hoped that it will reset all sessions but unfortunately, even after a reboot the error persists. Disabling and re-enabling the community document server and onlyoffice in the application overview does not help as well.

Is there a possibility to hard reset all sessions?

Thanks!

Nextcloud version: 19.0.4
PHP version: 7.4.12
Community document server version: 0.1.8
Onlyoffice version: 6.1.0

**Comment by rot666** [comment]
Did you find out how to?

**Comment by drudgede** [comment]
> Did you find out how to?

Well... somehow. after a nextcloud Update (I guess to version 20), the issue was gone and once reoccurred until I updated Nextcloud again. So somehow, the counter is resetted on an update. However, I have no idea how to manually solve this issue if no update is available.

**Comment by rot666** [comment]
I spent hours searching how to reset the connections. Also weird is that I only have 2 users that almost never open documents.

**Comment by drudgede** [comment]
Yes, the same holds for me and I also have no idea for a workaround. I don't even have 20 users.

**Comment by luilegeant** [comment]
Hello,
I have a similar problem and could trace back a little the situation.

# When it does work
When I authenticate with a local account (you guessed for my test it was `me.admin`), using onlyoffice + community document server app, i can edit my document on my browser just fine.

# When it doesn't work
When I authenticate with Social Login (see setup bellow), when i try to edit the same document (shared between the two account) i get the error _"The community document server only supports up to 20 concurrent sessions"_.

# Setup
- Nextcloud docker image: nextcloud:20.0.8-apache
- Mariadb docker image: mariadb:10.5.8
- Only office nextcloud app: https://github.com/ONLYOFFICE/onlyoffice-nextcloud
- Community document server app: https://github.com/nextcloud/documentserver_community
- Social login app (to use OIDC for authentication and authorization) : https://github.com/zorn-v/nextcloud-social-login
- Identity provider keycloak docker image: jboss/keycloak:12.0.1
- nginx as reverse proxy (for multi domain reverse proxying and https) docker image: nginx

# Findings:
- docker logs on the identity provider container: nothing useful
- docker logs on the nextcloud container: nothing useful
- docker logs on the reverse proxy container: nothing useful
- the value of my `oc_users.uid` is composed of the identity provider name (18 chars) concatenated with an hyphen then with a uid (see guid format with hyphen like `00000000-0000-0000-0000-000000000000`), which makes a total length of 55 char.
- Nextcloud admin logs: at route `/settings/admin/logging` (top right menu > settings > Logging)
Now it gets interresting (I redacted private data and replaced them by letter):
```log
[index] Error: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE `oc_documentserver_sess` SET `last_seen` = ?, `user` = ?, `user_original` = ?, `username` = ?, `readonly` = ? WHERE `session_id` = ?' with params [a, "b", "b", "c", false, "d"]:
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'user' at row 1 at <<closure>>
```
You see the field `user` and `user_original` (`varchar(64)`) that the call is trying to insert is not the same value as in `oc_users.uid` otherwise the value would fit, there is something appended just before the `oc_users.uid` value that makes it too big (by a few characters).
I could not figure out the source, but the value is 12 char long (looks random) concatenated with an underscore to the above.

# quick & dirty fix
By extending the "offending" field by a few (doubling it here) it can load the editor (not the file yet).
```sql
alter table `oc_documentserver_sess` modify `user` varchar(128);
alter table `oc_documentserver_sess` modify `user_original` varchar(128);
```
After looking in the logs (after step above), it seems that another table isn't being nice, back at altering the db:
```sql
alter table `oc_documentserver_changes` modify `user` varchar(128);
alter table `oc_documentserver_changes` modify `user_original` varchar(128);
```
Let's reload the same file, the logs are now complaining about another table, let's modify the db again:
```sql
alter table `oc_documentserver_locks` modify `user` varchar(128);
```
And :tada: I'm back on track ! I hope this helps you too.

If you need more details to debug this, lets me know.
