### ISSUE TITLE
Trying to add a font

### ISSUE THREAD

**Issue by davidcheeeese** [nextcloud/documentserver_community#20]
Hello, 
I'm trying to a fonts used in my documents 
https://github.com/powerline/fonts/tree/master/Monofur

I create a folder in core-fonts and add ttf files.
And edit: documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin/AllFonts.js

To add the fonts at the end of the font-file list

"../../../core-fonts/Monofur/Monofur Italic for Powerline.ttf,
"../../../core-fonts/Monofur/Monofur Bold for Powerline.ttf,
"../../../core-fonts/Monofur/Monofur for Powerline.ttf

and add an entry in font infos with as number position in the list

["Monofur for Powerline",208,0,-1,-1,-1,-1,-1,-1],
["Monofur Bold for Powerline",209,0,-1,-1,-1,-1,-1,-1],
["Monofur Italic for Powerline",210,0,-1,-1,-1,-1,-1,-1],

but it's not working.
Can you tell me what I miss ?

Thanks in advance

**Comment by tgurr** [comment]
@davidcheeeese thanks for that info, I tried to do the same with another font and your post was a great help, I found that there's also another file with font entries at `documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/common/AllFonts.js`
With the font infos added there as well onlyoffice seems to jump to the right font entry when clicking on said font in a document and also shows the fontname correctly.

There are two issues whoever
* the fonts don't seem to be visualised correctly
* the drop down list entries for the fonts are all white/empty.

It would be nice to have a way to just drop some ttf files into a directory instead of having to edit actual code which has to be redone after every update.

**Comment by davidcheeeese** [comment]
Thanks @tgurr 
I checked on the onlyoffice website, there is a sh to launch to add fonts https://helpcenter.onlyoffice.com/de/server/linux/document/install-fonts.aspx
but is not on the documentserver implementation
I will maybe try to implement it.

I find a trace of .ttf on this file too
documentserver_community/3rdparty/onlyoffice/documentserver/sdkjs/slide/sdk-all.cache

**Comment by icewind1991** [comment]
Font management will be added to the next release (https://github.com/nextcloud/documentserver_community/commit/f3714db8060ad34e72aad43082ca0977b65d07c3)

**Comment by davidcheeeese** [comment]
Great news, many thanks !
