### ISSUE TITLE
OnlyOffice no nextcloud

### ISSUE THREAD

**Issue by Wfrias** [nextcloud/documentserver_community#209]
Olá,

Estou utilizando o Community Document Server em minhas instâncias nexcloud, e quando altero algum arquivo .xls ou .doc dentro da  instância nextcloud, observei que tem um delay muito grande ( por volta de 10 minutos)  para que alteração seja sincronizada com o arquivo quando o mesmo é aberto através do sincronizador ou através mapeamento. Mas quando a alteração é realizada através do computador a partir do sincronizador ou compartilhamento, é refletida imediato atráves da instância Nextcloud.Algum sabe se tem algo que pode ser realizado para solução deste problema, ou é algo de no servidor da comunidade?
Hi,

I am using the Community Document Server on my nexcloud instances, and when I change an .xls or .doc file within the nextcloud instance, I noticed that it has a very long delay (around 10 minutes) for the change to be synchronized with the file when the it is even opened through the synchronizer or through mapping. But when the change is made through the computer from the synchronizer or sharing, it is reflected immediately through the Nextcloud instance. Does anyone know if there is anything that can be done to solve this problem, or is it something on the community server?

**Comment by Fiodin** [comment]
This sounds like the Problem in #100

**Comment by arnowelzel** [comment]
Do yourself a favour and use OnlyOffice in a docker container or use a standalone OnlyOffice server and the integration app by Ascensio. The version provided by Nextcloud seems to be more a tech demo but not very reliable.

 Also see:
 
https://hub.docker.com/r/onlyoffice/documentserver/
https://apps.nextcloud.com/apps/onlyoffice
https://arnowelzel.de/en/onlyoffice-in-nextcloud-the-current-status

**Comment by baku104788** [comment]
> 
> 
> Do yourself a favour and use OnlyOffice in a docker container or use a standalone OnlyOffice server and the integration app by Ascensio. The version provided by Nextcloud seems to be more a tech demo but not very reliable.
> 
> Also see:
> 
> https://hub.docker.com/r/onlyoffice/documentserver/
> https://apps.nextcloud.com/apps/onlyoffice
> https://arnowelzel.de/en/onlyoffice-in-nextcloud-the-current-status

I really don't think a suggestion to use a different solution is a valid reply. We have this functionality built in for a reason. If it isn't going to be supported or maintained then it should be removed.  There are plenty of us out there that don't want to mess with the complexity of setting up an independent instance of onlyoffice server and the reverse proxies that are required as a result. 

Now if there was a document walking through that process for those that were willing that would be one thing.  Otherwise we need to expect that released features will work and if they don't - fix them.
