### ISSUE TITLE
NC22 Internal Server Error on accessing public link - incompatible with Deck App?

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud/documentserver_community#223]
- If accessing a public link in a browser where I'm not logged in, Nextcloud shows an internal server error, if the app "Deck" is enabled. Otherwise the document opens nomrally and I can work with it.
- If I'm logged it and access the public link I just get the message about the reached connection limit.
- If I'm logged in and access the document directly in the cloud without public link, then I also get the reached connection limit message.
- The connection limit can't be reached - This happens also directly after a server restart. Also the connection limit ever hasn't reched, as long as the cloud instance exists. And, if the Deck app is disabled, I can access the document with public link, as long as I'm not logged in.

~One example link:~ (Disabled Deck, so the link is working again)
https://cloud.pilzinsel64.com/apps/onlyoffice/s/nZ3J2YBwSQgdfk5

Server error:
```
{"reqId":"iza4hRqHDnvkokZzG3Tm","level":3,"time":"2021-07-08T19:15:57+00:00","remoteAddr":"5.100.37.185","user":"--","app":"index","method":"GET","url":"/apps/onlyoffice/s/nZ3J2YBwSQgdfk5","message":"OC\\Group\\Manager::getUserIdGroupIds(): Argument #1 ($uid) must be of type string, null given, called in /var/www/vhosts/pilzinsel64.com/cloud.pilzinsel64.com/lib/private/Group/Manager.php on line 316","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0","version":"22.0.0.11","exception":{"Exception":"TypeError","Message":"OC\\Group\\Manager::getUserIdGroupIds(): Argument #1 ($uid) must be of type string, null given, called in /var/www/vhosts/pilzinsel64.com/cloud.pilzinsel64.com/lib/private/Group/Manager.php on line 316","Code":0,"Trace":[{"file":"/var/www/vhosts/pilzinsel64.com/cloud.pilzinsel64.com/lib/private/Group/Manager.php","line":316,"function":"getUserIdGroupIds","class":"OC\\Group\\Manager","type":"->"},{"file":"/var/www/vhosts/pilzinsel64.com/cloud.pilzinsel64.com/apps/deck/lib/Service/PermissionService.php","line":294,"function":"isInGroup","class":"OC\\Group\\Manager","type":"->"},{"file":"/var/www/vhosts/pilzinsel64.com/cloud.pilzinsel64.com/apps/deck/lib/Capabilities.php","line":53,"function":"canCreate","class":"OCA\\Deck\\Service\\PermissionService","type":"->"},{"file":"/var/www/vhosts/pilzinsel64.com/cloud.pilzinsel64.com/lib/private/CapabilitiesManager.php","line":69,"function":"getCapabilities","class":"OCA\\Deck\\Capabilities","type":"->"},{"file":"/var/www/vhosts/pilzinsel64.com/cloud.pilzinsel64.com/lib/private/Template/JSConfigHelper.php","line":190,"function":"getCapabilities","class":"OC\\CapabilitiesManager","type":"->"},{"file":"/var/www/vhosts/pilzinsel64.com/cloud.pilzinsel64.com/lib/private/TemplateLayout.php","line":220,"function":"getConfig","class":"OC\\Template\\JSConfigHelper","type":"->"},{"file":"/var/www/vhosts/pilzinsel64.com/cloud.pilzinsel64.com/lib/private/legacy/OC_Template.php","line":182,"function":"__construct","class":"OC\\TemplateLayout","type":"->"},{"file":"/var/www/vhosts/pilzinsel64.com/cloud.pilzinsel64.com/lib/public/AppFramework/Http/TemplateResponse.php","line":204,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/var/www/vhosts/pilzinsel64.com/cloud.pilzinsel64.com/lib/public/AppFramework/Http/Template/PublicTemplateResponse.php","line":154,"function":"render","class":"OCP\\AppFramework\\Http\\TemplateResponse","type":"->"},{"file":"/var/www/vhosts/pilzinsel64.com/cloud.pilzinsel64.com/lib/private/AppFramework/Http/Dispatcher.php","line":171,"function":"render","class":"OCP\\AppFramework\\Http\\Template\\PublicTemplateResponse","type":"->"},{"file":"/var/www/vhosts/pilzinsel64.com/cloud.pilzinsel64.com/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/vhosts/pilzinsel64.com/cloud.pilzinsel64.com/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/vhosts/pilzinsel64.com/cloud.pilzinsel64.com/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/vhosts/pilzinsel64.com/cloud.pilzinsel64.com/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/vhosts/pilzinsel64.com/cloud.pilzinsel64.com/lib/private/Group/Manager.php","Line":333,"CustomMessage":"--"},"id":"60e74eed3ff5a"}
```

**Comment by Henk57** [comment]
Same issue with one of our NC clouds v22.0.0. Seems to be the same isue as https://github.com/nextcloud/groupfolders/issues/267 from feb 2019.

**Comment by Pilzinsel64** [comment]
Exactly. I'm maintaining three NC instances. One is still NC21 and the two other NC22. One of them NC22 has that issue, the other not. Bot both have nearly the same apps installed and are configured the same and are on the same kind of V-Server at the same host.

**Comment by Henk57** [comment]
This problem is also here: https://github.com/nextcloud/deck/issues/3194 

It looks as if it has something to do with 'Groups' that are empty; defined groups that have no users.
And indeed, that is different between 2 installs. I will aad a fake user to empty groups.
![image](https://user-images.githubusercontent.com/13239537/127572708-5a181cc7-88a6-49e7-af7c-e507964cf4c6.png)
I have to check where AllUsers and users come from. That is different on other installs.

**Comment by Henk57** [comment]
This seems not to work yet. I will occ the database a.s.o. later.

**Comment by martin-77** [comment]
> 
> 
> This problem is also here: [nextcloud/deck#3194](https://github.com/nextcloud/deck/issues/3194)
> 
> It looks as if it has something to do with 'Groups' that are empty; defined groups that have no users.
> And indeed, that is different between 2 installs. I will aad a fake user to empty groups.
> ![image](https://user-images.githubusercontent.com/13239537/127572708-5a181cc7-88a6-49e7-af7c-e507964cf4c6.png)
> I have to check where AllUsers and users come from. That is different on other installs.

In our Instance are no empty groups, even though we get the internal Server Error #3194

**Comment by Henk57** [comment]
Removing empty groups had no effect, indeed.
OCC options extecuted, repair, database tables a.s.o. No issues found. No effect at all.
And I think there must be something wrong in the database since only one NC instance has this problem.

Disabled nearly all apps, this had no effect.
**Only disabling Deck resulted in a login screen and no error.**

While occ'ing and looking at the logs I discovered more errors:

The DECK error:
Argument 1 passed to OC\Group\Manager::getUserIdGroupIds() must be of the type string, null given

The NEWS error:
Error: mkdir(): Permission denied at /home/xxxxxx/domains/xxxxxx.nl/public_html/cloud/apps/news/lib/AppInfo/Application.php#95

The CIRCLES check:
Loopback address error
'occ circles:test' is a command in the occ help list, but that one is no longer valid in NC22

And in other posts is stated that the NC22.0.1 beta is not solving the DECK trouble.

I'd expect a stable release to be stable. That is not the case since Deck, Circles and more are 'reccommended' apps.
All my NC clouds run on same server and php4 version.
And NC 23 is already under development. NC is going to fast in major updates in my opinion. Some problems seem to repeat from versions <20. 

So please, priotarize solving this 'login bug'.
