### ISSUE TITLE
compatibile with Nextcloud 23

### ISSUE THREAD

**Issue by francescob** [nextcloud/documentserver_community#246]
Any plan for the release? at the moment this is the only plugin I have installed that doesn't support the latest Nextcloud version

**Comment by koebln** [comment]
Urgent! The upgrade process from Nextcoud 22 did not show this incompatible App. So, Onlyoffice is not working any more...

**Comment by roru69** [comment]
Same Here,

I want to upgrade to Nextcloud 23, but this app is incompatible with version 23 according to Nextcloud. I use it quite a lot.

Regards, RR69

**Comment by david-samson** [comment]
Same. No need to rush the update, just need to know if it's in the works or at least planned.

**Comment by s3lph** [comment]
Hi, this has been open for quite some while now. Is there an update planned? Is this app even still maintained? The last commit on master and the last release have were about half a year ago.

**Comment by BeardElk** [comment]
Wondering the same thing here. 
When I install it and set everything up I´m presented with a blank screen when I try to edit a simple txt.

**Comment by s3lph** [comment]
In case anyone's wondering: The latest version, 0.1.11, works flawlessly in Nextcloud 23 when you edit maxVersion in appinfo/info.xml. Of course this is a bit of a hassle, since you can't simply update the app in Nextcloud, but it's still a lot less involved than deploying a full standalone OnlyOffice Document Server.

**Comment by greavette** [comment]
Is the Community Document Server project dead?  Why hasn't this been updated for Nextcloud 23 yet?  Nextcloud has promoted the ability to view/edit documents from within Nextcloud and our small office uses it heavily.  I know this isn't a supported Feature by Nextcloud but is there a reason why no one has been assigned to update this to the latest version of Nextcloud?

**Comment by archont00** [comment]
Wondering what the advantage of this repo compared to "Comunity Document Server" at this link https://www.onlyoffice.com/download-docs.aspx is...

(I use the docker version, though.)

**Comment by s3lph** [comment]
@archont00 the code in this repo is for a Nextcloud app that ships a bundled version of OnlyOffice - much less trouble to set up, basically a single click in Nextcloud Apps.

**Comment by azmeuk** [comment]
It seems [v0.1.12](https://github.com/nextcloud/documentserver_community/releases/tag/v0.1.12) fixes the issue.

**Comment by greavette** [comment]
Agreed @azmeuk , the latest version does fix this issue.

Thank you.

**Comment by stevejordi** [comment]
Can you actually open documents?
I have tried for weeks.
Each time I click an XLSX or DOCX doc, I have the logo and then a dialog box always telling the same thing:
An error has occurred while opening the file
Press OK to return to document list

**Comment by Githopp192** [comment]
i'm running documentserver_community: **0.1.12 on NC: 22.2.6**

This errors appearing since months (when not saying years) and were never fixed.

[documentserver_community] Error: Error while applying changes for document 1146680491
at 2022-03-28T20:35:05+02:00

OCA\DocumentServer\Document\DocumentConversionException: Uncaught TypeError: Cannot read property 'En' of undefined 

DoctRenderer:<result><error index="0" /></result> namespace error : Namespace prefix wp14 on sizeRelH is not defined rawingml/2006/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="margin" ^ namespace error : Namespace prefix wp14 on pctWidth is not defined ain"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="margin"><wp14:pctWidth ^ namespace error : Namespace prefix wp14 on sizeRelV is not defined 4:pctWidth>0</wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="margin" ^ namespace error : Namespace prefix wp14 on pctHeight is not defined 14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="margin"><wp14:pctHeight ^ namespace error : Namespace prefix wp14 on sizeRelH is not defined rawingml/2006/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="margin" ^ namespace error : Namespace prefix wp14 on pctWidth is not defined ain"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="margin"><wp14:pctWidth ^ namespace error : Namespace prefix wp14 on sizeRelV is not defined 4:pctWidth>0</wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="margin" ^ namespace error : Namespace prefix wp14 on pctHeight is not defined 14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="margin"><wp14:pctHeight ^

OCP\Files\NotFoundException: /appdata_ocnudqtqmhau/documentserver_community/doc_1664756893/owner
/var/www/html/nextcloud/lib/private/Files/Node/Folder.php - line 146:

OC\Files\Node\Root->get()

/var/www/html/nextcloud/lib/private/Files/SimpleFS/SimpleFolder.php - line 75:

OC\Files\Node\Folder->get()

/var/www/html/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php - line 137:

OC\Files\SimpleFS\SimpleFolder->getFile()

/var/www/html/nextcloud/apps/documentserver_community/lib/Document/SaveHandler.php - line 58:

OCA\DocumentServer\Document\DocumentStore->saveChanges()

/var/www/html/nextcloud/apps/documentserver_community/lib/BackgroundJob/Cleanup.php - line 71:

OCA\DocumentServer\Document\SaveHandler->flushChanges()

/var/www/html/nextcloud/lib/public/BackgroundJob/Job.php - line 79:

OCA\DocumentServer\BackgroundJob\Cleanup->run()

/var/www/html/nextcloud/cron.php - line 149:

OCP\BackgroundJob\Job->execute()

**Comment by aaronhuggins** [comment]
> In case anyone's wondering: The latest version, 0.1.11, works in Nextcloud 23 when you edit maxVersion in appinfo/info.xml. Of course this is a bit of a hassle, since you can't simply update the app in Nextcloud, but it's still a lot less involved than deploying a full standalone OnlyOffice Document Server.
> 
> OTOH, trying to build this app with OODS 7.0.0 somehow causes a segfault in the `allfontsgen` step, but that seems to be an upstream issue; even segfaults when running this command inside the upstream container.

@s3lph I figured out that this is a quirk of how OO is compiling. With version OO DS 7.x.x, the files get hard-linked to search `lib64` and their relative path regardless of cwd. I think it's a byproduct of the compiler flags, but whatever. I also found that the Docker container's binaries were no longer portable, so I switched to extracting from the official rpm.

PR #274 should fix the segfaults during packaging and in prod.
