### ISSUE TITLE
How close the office after working on a file?

### ISSUE THREAD

**Issue by Kitanit** [nextcloud/documentserver_community#275]
![image](https://user-images.githubusercontent.com/65107731/201013268-659e4b1d-46f6-46f5-9568-ab4fcdba948c.png)

**Comment by mrbaseman** [comment]
Just navigate away with the black menu bar in the very top region. The changes made in onlyoffice should be saved automatically in the background.

**Comment by Kitanit** [comment]
> Just navigate away with the black menu bar in the very top region. The changes made in onlyoffice should be saved automatically in the background.

I understand, thank you it would just be nice to have a native exit button, as without it you can't exit a document if you open it in Talk, for example

**Comment by mrbaseman** [comment]
I wrote the changes should be saved automatically, but I should add that there is a problem, that currently files are sometimes not saved to the file system #281

**Comment by brlarini** [comment]
This was an issue to me as well.

I had finished working on a document, clicked to "return to file location" and downloaded the document.
Then I opened the file in a local editor and it didn't contain the changes I made. Already getting nervous to have lost them, I updated NC page and now it showed an updated datetime on the file. Then downloaded it again, and this time it did bring the changes.

I'm not sure, but using the "return to file location" doesn't work quite as a close button, because it seems to put the document on the background rather than closing it and committing to the disk.
It would be nice if this was as less confusing as possible to your average user.

Thanks!
