### ISSUE TITLE
please update documentserver_community to 7.3.x

### ISSUE THREAD

**Issue by shurakr** [nextcloud/documentserver_community#299]

**Comment by elhossary** [comment]
+1

**Comment by chadek** [comment]
Checkout [this pr](https://github.com/nextcloud/documentserver_community/pull/303)

**Comment by chadek** [comment]
I've been trying to update to last Onlyoffice version (7.4.1) but since 7.3.0, they changed a vendor sockjs to socket.io and it drops an error while trying to load a socket.io component on loading a document. I have been digging a bit and [this thread](https://forum.onlyoffice.com/t/onlyoffice-7-3-websocket-path-changed/3767/10) might help resolve this for good.

If someone have any clue, help is welcome here. I'll be investigating more when I'll find some time for that.

**Comment by chadek** [comment]
Opened a new one here #312 asking for help to get to v8.0.0
